[package]
name = "space_team_irl"
version = "0.1.0"
authors = ["Mark Hildreth <mark.k.hildreth@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
feather_m0 = "0.6.0"
panic-halt = "0.2.0"
atsamd-hal = "0.8.2"
embedded-hal = "0.2.3"
bitflags = "1.2.1"

[profile.release]
debug = true
lto = true
opt-level = "s"
