[package]
name = "space_trouble"
version = "0.1.0"
authors = ["Mark Hildreth <mark.k.hildreth@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
feather_m0 = { version = "0.6.0", features = ["unproven"] }
panic-halt = "0.2.0"
atsamd-hal = "0.8.2"
embedded-hal = "0.2.3"
hd44780-driver = { git = "https://github.com/JohnDoneth/hd44780-driver", branch = "master" }
cortex-m-rt = "0.6.12"
cortex-m = "0.6.2"
heapless = "0.5.3"
rand = { version = "0.7.3", default-features = false, features = ["small_rng"] }
st_logic = { path = "st_logic" }

[profile.release]
codegen-units = 1
lto = true

